language: python

python:
  - "2.7"

env:
  - VERSION="6.1"

virtualenv:
  system_site_packages: true

before_install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly ${VERSION}
  - pip install coveralls flake8
 
script:
    - travis_run_flake8
    - travis_run_tests ${VERSION}

after_success:
  coveralls
